#+TITLE: ImbBench
#+AUTHOR: Anderson Mattheus Maliszewski
#+STARTUP: overview indent
#+TAGS: noexport(n) deprecated(d)
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+SEQ_TODO: TODO(t!) STARTED(s!) WAITING(w!) | DONE(d!) CANCELLED(c!) DEFERRED(f!)

*Imbalance Benchmark (ImbBench)* is a set of MPI-based applications,
created by the Ph.D. Student Eduardo Roloff, that simulate several
behaviors in terms of process loads. ImbBench was designed with the
heterogeneity of the cloud in mind, and its goal is to help the user to
choose the most suitable configuration to execute an application in the
cloud. ImbBench distributes the load among all the available processes
according to a preselected imbalance pattern.

Below are listed a quick hands-on, composed by required dependencies
and utilization. Further information about the benchmark can be seen at
the Publication session.

* Installation
To execute this benchmark some packages need to be installed,
which are:
- openmpi-bin: Parallel code executor program (mpirun).
- libopenmpi-dev: Necessary to develop parallel programs based on MPI
  (mpicc command...)  

Install the packages:
#+begin_src shell :results output :exports both
sudo apt install openmpi-bin libopenmpi-dev  
#+end_src

Clone and compile it:
#+begin_src shell :results output :exports both
git clone --recursive https://github.com/Roloff/ImbBench.git
cd ImbBench; mkdir bin; make
#+end_src

* Utilization
To execute the benchmark it is necessary to select specific
parameters, which are:

- Test - *CPU* and  *Memory* or Help.
- Patterns - *Balanced*, *Linear*, *Amdahl*, *2Level*, *4Level*, *8Level* or Help
- Microbenchmark - *Rand*, *Sort* and *BST*

The line command for execution will be like this:
#+begin_src shell :results output :exports both
mpirun -np $Processes bin/imb $Test $Pattern $Microbenchmark
#+end_src

Future updates of this benchmark are inteded to bring tests using I/O
and Network.

* Publications
- Eduardo Roloff, Matthias Diener, Luciano P. Gaspary, Philippe
  O. A. Navaux. *Exploiting Load Imbalance Patterns for Heterogeneous*
  *Cloud Computing Platforms*. International Conference on Cloud
  Computing and Services Science (CLOSER), 2018. [[https://doi.org/10.5220/0006807502480259][DOI]]



